version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0  # Use .NET 8
    commands:
      - echo "Installing dependencies..."
      - dotnet --version

  pre_build:
    commands:
      - echo "Restoring dependencies..."
      - dotnet restore

  build:
    commands:
      - echo "Building .NET 8 application..."
      - dotnet publish -c Release -o ./publish

artifacts:
  files:
    - '**/*'
  base-directory: .
